Trunk/Main/Sources/Selise.MySelise/Selise.Web/Controllers/LeaveApplicationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Selise.Data.DatabaseContext;

namespace Selise.Web.Controllers
{
    using System.Security.Claims;

    [Authorize]
    public class LeaveApplicationController : Controller
    {
        private readonly mySeliseEntities db;
        private readonly string claimedEmailAddress;
        private readonly Employee employee;

        public LeaveApplicationController()
        {
            db = new mySeliseEntities();

            var emailClaim = ClaimsPrincipal.Current.Claims.FirstOrDefault(c => c.Type.EndsWith("/emailaddress"));
            if (emailClaim == null) { return; }

            claimedEmailAddress = emailClaim.Value;
            if ( string.IsNullOrWhiteSpace(claimedEmailAddress)) { return; }

            employee = db.Employees.FirstOrDefault(e => e.OfficialEmail == claimedEmailAddress);
        }

        public ActionResult ListAllApplication()
        {
            var leaveApplications = db.LeaveApplications.Include(l => l.ApprovedByEmployee).Include(l => l.Employee).Where(l => l.EmployeeId == employee.Id);
            return View(leaveApplications.ToList());
        }

        // GET: LeaveApplication
        public ActionResult Index()
        {
            var leaveApplications = db.LeaveApplications.Include(l => l.ApprovedByEmployee).Include(l => l.Employee);
            return View(leaveApplications.ToList());
        }

        // GET: LeaveApplication/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LeaveApplication leaveApplication = db.LeaveApplications.Find(id);
            if (leaveApplication == null)
            {
                return HttpNotFound();
            }
            return View(leaveApplication);
        }

        // GET: LeaveApplication/Create
        public ActionResult Create()
        {
            ViewBag.ApprovedBy = new SelectList(db.Employees, "Id", "FullName");
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FullName");
            return View();
        }

        // POST: LeaveApplication/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EmployeeId,ApplicationDate,ApplicationType,StartFrom,EndTo,DaysApplied,DaysApproved,NoOfHalfDayLeave,IsApporved,Comment,ApprovedBy,ApprovedOn")] LeaveApplication leaveApplication)
        {
            if (ModelState.IsValid)
            {
                db.LeaveApplications.Add(leaveApplication);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ApprovedBy = new SelectList(db.Employees, "Id", "FullName", leaveApplication.ApprovedBy);
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FullName", leaveApplication.EmployeeId);
            return View(leaveApplication);
        }

        // GET: LeaveApplication/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LeaveApplication leaveApplication = db.LeaveApplications.Find(id);
            if (leaveApplication == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApprovedBy = new SelectList(db.Employees, "Id", "FullName", leaveApplication.ApprovedBy);
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FullName", leaveApplication.EmployeeId);
            return View(leaveApplication);
        }

        // POST: LeaveApplication/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EmployeeId,ApplicationDate,ApplicationType,StartFrom,EndTo,DaysApplied,DaysApproved,NoOfHalfDayLeave,IsApporved,Comment,ApprovedBy,ApprovedOn")] LeaveApplication leaveApplication)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leaveApplication).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApprovedBy = new SelectList(db.Employees, "Id", "FullName", leaveApplication.ApprovedBy);
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "FullName", leaveApplication.EmployeeId);
            return View(leaveApplication);
        }

        // GET: LeaveApplication/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LeaveApplication leaveApplication = db.LeaveApplications.Find(id);
            if (leaveApplication == null)
            {
                return HttpNotFound();
            }
            return View(leaveApplication);
        }

        // POST: LeaveApplication/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LeaveApplication leaveApplication = db.LeaveApplications.Find(id);
            db.LeaveApplications.Remove(leaveApplication);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Trunk/Main/Sources/Selise.MySelise/Selise.Web/Views/LeaveApplication/Create.cshtml
@using Selise.Data.DatabaseContext
@model Selise.Data.DatabaseContext.LeaveApplication

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LeaveApplication</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationDate, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationDate, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.ApplicationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaysApplied, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DaysApplied, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DaysApplied, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaysApproved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DaysApproved, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DaysApproved, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfHalfDayLeave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfHalfDayLeave, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfHalfDayLeave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsApporved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsApporved)
                    @Html.ValidationMessageFor(model => model.IsApporved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovedBy, "ApprovedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApprovedBy", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApprovedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApprovedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApprovedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Trunk/Main/Sources/Selise.MySelise/Selise.Web/Views/LeaveApplication/Delete.cshtml
@model Selise.Data.DatabaseContext.LeaveApplication

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LeaveApplication</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaysApplied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaysApplied)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaysApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaysApproved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfHalfDayLeave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfHalfDayLeave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApporved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApporved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovedByEmployee.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovedByEmployee.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.FullName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Trunk/Main/Sources/Selise.MySelise/Selise.Web/Views/LeaveApplication/Details.cshtml
@model Selise.Data.DatabaseContext.LeaveApplication

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>LeaveApplication</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartFrom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartFrom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaysApplied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaysApplied)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaysApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaysApproved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfHalfDayLeave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfHalfDayLeave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApporved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApporved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovedByEmployee.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovedByEmployee.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.FullName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back", "ListAllApplication", "LeaveApplication")
</p>

Trunk/Main/Sources/Selise.MySelise/Selise.Web/Views/LeaveApplication/Edit.cshtml
@model Selise.Data.DatabaseContext.LeaveApplication

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LeaveApplication</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartFrom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartFrom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartFrom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaysApplied, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DaysApplied, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DaysApplied, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaysApproved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DaysApproved, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DaysApproved, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfHalfDayLeave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfHalfDayLeave, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfHalfDayLeave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsApporved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsApporved)
                    @Html.ValidationMessageFor(model => model.IsApporved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovedBy, "ApprovedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApprovedBy", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApprovedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApprovedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApprovedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Trunk/Main/Sources/Selise.MySelise/Selise.Web/Views/LeaveApplication/Index.cshtml
@model System.Collections.Generic.IEnumerable<Selise.Data.DatabaseContext.LeaveApplication>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartFrom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DaysApplied)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DaysApproved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoOfHalfDayLeave)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsApporved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApprovedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApprovedByEmployee.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Employee.FullName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartFrom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DaysApplied)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DaysApproved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoOfHalfDayLeave)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsApporved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApprovedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApprovedByEmployee.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.FullName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Trunk/Main/Sources/Selise.MySelise/Selise.Web/Views/LeaveApplication/ListAllApplication.cshtml
@model System.Collections.Generic.IEnumerable<Selise.Data.DatabaseContext.LeaveApplication>

@{
    ViewBag.Title = "Leave Application List";
}

<h2>My Leave Application List</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartFrom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DaysApplied)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsApporved)
        </th>
        <th>
            Action
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartFrom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DaysApplied)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsApporved)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.Id })
        </td>
    </tr>
}

</table>